version: '3.8'

services:
  mongo1:
    image: mongo
    command: ["mongod", "--replSet", "rs0"]
    ports:
      - 27017:27017

  secondary:
    image: mongo
    ports:
      - 27018:27017

  therd:
    image: mongo
    ports:
      - 27019:27017